// import React from "react";

// const Header = () => {
//   return <p>header</p>;
// };
// export default Header;

import React from "react";
import styles from "../../styles/Header.module.css";

const Header = () => (
  <div className="flex flex-col h-screen">
    <div className="flex justify-around	items-center">
      <h1> hello world</h1>
      <ul className={styles.nav}>
        <li>home</li>
        <li>about</li>
        <li>contact</li>
        <li>portfolio</li>
      </ul>
    </div>
    <div className={styles.banner}>
      <p className={styles.para}>
        <h1>Banner Section</h1>
        webpack finds all relative module references in CSS (they start with ./)
        and replaces them with the final paths from the compiled bundle. If you
        make a typo or accidentally delete an important file, you will see a
        compilation error, like when you import a non-existent JavaScript
        module. The final filenames in the compiled bundle are generated by
        webpack from content hashes. If the file content changes in the future,
        webpack will give it a different name in production so you don’t need to
        worry about long-term caching of assets.
      </p>
      <img
        className="mentor-img"
        src="https://preview.colorlib.com/theme/universityedu/assets/img/gallery/xabout1.jpg.pagespeed.ic.sBdkEuDZM5.webp"
        height="220px"
        width="200px"
        alt=""
      />
    </div>
  </div>
);

export default Header;
